### ISSUE TITLE
Compile errors due to dependency problems with dep

### ISSUE THREAD

**Issue by savely-krasovsky** [gramework/gramework#43]
I use dep for my projects, with usual `dep` use it cannot download right dependencies automatically. Didn't check it with `go get` and others managers, maybe related to them too.

## Expected Behavior

After `den ensure` project should compile without any errors.

## Current Behavior

It cannot because of updated `lego` and `fasthttp` libs.

## Possible Solution

Edit manually `Gopkg.toml` by adding this:
```toml
[[override]]
  name = "github.com/xenolf/lego"
  version = "0.5.0"

[[override]]
  name = "github.com/valyala/fasthttp"
  version = "1.0.0"
```
and try `dep ensure` again (you can also try to delete `Gopkg.lock` and `vendor` files before).

## Steps to Reproduce (for bugs)

1. Use `dep`
2. Download dependencies by using `dep ensure` command

## Context

I wanted to get it work with dep because vgo on 1.10 is pretty unstable for production use.

## Your Environment

* Version used: v1.2.0
* Environment name and version (e.g. Go1.9 on CentOS 7, kernel 4.11.2): Fedora 28, Go 1.10.3, 4.18.12
* Server type and version: net/http
* Operating System and version: Fedora 28
* Link to your project: none
